# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-09-01 22:09
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Lake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=255, unique=True)),
                ('logo_path', models.ImageField(upload_to='img')),
                ('url', models.URLField(blank=True, max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='StationMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('name', models.CharField(max_length=256, unique=True)),
                ('long_name', models.CharField(blank=True, max_length=256)),
                ('recovered', models.BooleanField()),
                ('buoy_info', models.TextField()),
                ('alternate_id', models.CharField(max_length=256, null=True, unique=True)),
                ('buoy_alert', models.CharField(blank=True, max_length=256)),
                ('meta_glos', models.URLField(blank=True, max_length=512)),
                ('wq_only', models.BooleanField()),
                ('wq_and_wx', models.BooleanField()),
                ('buoy_owner', models.CharField(max_length=256)),
                ('sofar_spotter_id', models.CharField(blank=True, max_length=256)),
                ('uglos_link', models.BooleanField()),
                ('webcam_link', models.URLField(blank=True, max_length=512)),
                ('contact', models.ManyToManyField(to='Buoy_tool.Contact')),
                ('lake_override', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Buoy_tool.Lake')),
            ],
        ),
    ]
