# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-09-01 23:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buoy_tool', '0002_stationmeta_sponsor_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='lake',
            name='name',
            field=models.CharField(default='Lake Fakenews', max_length=256, unique=True),
            preserve_default=False,
        ),
    ]
